import { useEffect, useRef, useState } from 'react';

type PagefindResult = {
  id: string;
  data: () => Promise<{
    url: string;
    meta: { title?: string };
    excerpt: string;
  }>;
};

type Pagefind = {
  search: (q: string, opts?: { filters?: Record<string, string> }) => Promise<{ results: PagefindResult[] }>;
};

export default function SearchDialog({ locale, placeholder }: { locale: 'zh' | 'en'; placeholder: string }) {
  const [open, setOpen] = useState(false);
  const [q, setQ] = useState('');
  const [results, setResults] = useState<{ url: string; title: string; excerpt: string }[]>([]);
  const inputRef = useRef<HTMLInputElement>(null);
  const pagefindRef = useRef<Pagefind | null>(null);

  useEffect(() => {
    function onKey(e: KeyboardEvent) {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        setOpen((v) => !v);
      }
      if (e.key === 'Escape') setOpen(false);
    }
    function onClick() {
      const btn = document.getElementById('open-search');
      btn?.addEventListener('click', () => setOpen(true));
    }
    onClick();
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  useEffect(() => {
    if (open) inputRef.current?.focus();
  }, [open]);

  useEffect(() => {
    if (!open || !q.trim()) { setResults([]); return; }
    let cancelled = false;
    (async () => {
      if (!pagefindRef.current) {
        // Pagefind is generated by `pagefind --site dist` into /pagefind/pagefind.js
        // at build time. Bypass Vite's static-analysis (it rejects imports of files
        // under /public) by constructing the import via `new Function`. In dev, a
        // stub at public/pagefind/pagefind.js keeps this resolvable.
        const dynamicImport = new Function('p', 'return import(p)') as (p: string) => Promise<Pagefind>;
        pagefindRef.current = await dynamicImport('/pagefind/pagefind.js');
      }
      const search = await pagefindRef.current.search(q, { filters: { lang: locale } });
      const data = await Promise.all(search.results.slice(0, 8).map((r) => r.data()));
      if (cancelled) return;
      setResults(data.map((d) => ({ url: d.url, title: d.meta.title ?? d.url, excerpt: d.excerpt })));
    })().catch(() => { /* swallow on dev where /pagefind/ doesn't exist */ });
    return () => { cancelled = true; };
  }, [q, open, locale]);

  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center pt-24 bg-black/40" onClick={() => setOpen(false)}>
      <div
        className="w-full max-w-xl rounded-xl bg-[rgb(var(--color-card))] border border-[rgb(var(--color-border))] shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        <input
          ref={inputRef}
          type="text"
          placeholder={placeholder}
          value={q}
          onChange={(e) => setQ(e.target.value)}
          className="w-full px-4 py-3 bg-transparent border-b border-[rgb(var(--color-border))] outline-none"
        />
        <ul className="max-h-96 overflow-y-auto">
          {results.length === 0 && q.trim() && (
            <li className="px-4 py-3 text-sm text-[rgb(var(--color-muted))]">No results for "{q}"</li>
          )}
          {results.map((r) => (
            <li key={r.url}>
              <a href={r.url} className="block px-4 py-3 hover:bg-[rgb(var(--color-bg))] border-b border-[rgb(var(--color-border))] last:border-0">
                <div className="font-medium">{r.title}</div>
                <div className="text-sm text-[rgb(var(--color-muted))] mt-1" dangerouslySetInnerHTML={{ __html: r.excerpt }} />
              </a>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
}
